"""scripts/sync_codex_mirror.py — .claude/skills의 Codex 미러(.codex/skills) 생성

Codex(codex CLI)는 Claude Code와 달리 skill runtime이 없어 `.claude/skills/`를
자동 로드하지 못한다. 그래서 AGENTS.md가 가리킬 수 있도록 `.claude/skills`의
생성 미러를 `.codex/skills`에 만든다.

`.claude/skills`가 단일 진실의 원천(SSOT). `.codex/skills`는 생성물이다 —
텍스트 파일 안의 ".claude/skills" 토큰만 ".codex/skills"로 치환하고 나머지는
byte-identical 복사. 스킬 수정 후 반드시 재실행한다.

사용법:
    python scripts/sync_codex_mirror.py          # 미러 재생성
    python scripts/sync_codex_mirror.py --check  # stale이면 exit 1 (쓰지 않음)
"""
from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path

# scripts/sync_codex_mirror.py: parents[0]=scripts [1]=repo root
REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / ".claude" / "skills"
DST = REPO_ROOT / ".codex" / "skills"

TEXT_SUFFIXES = {".md", ".py", ".sh", ".json", ".txt", ".svg", ".cfg",
                 ".toml", ".yml", ".yaml", ".ini"}
EXCLUDE_NAMES = {"__pycache__", ".DS_Store"}
# host-only 스킬 제외용 (예: slide의 codex-image). 이 repo엔 없음.
EXCLUDE_REL_PREFIXES: set[tuple[str, ...]] = set()
OLD_TOKEN = ".claude" + "/skills"
NEW_TOKEN = ".codex" + "/skills"
GENERATED_MARKER = f"""# Generated Codex Skills Mirror

This directory is generated by `sync_codex_mirror.py`.
Do not hand-edit files under `{NEW_TOKEN}`.
Edit `{OLD_TOKEN}`, then regenerate this mirror.
"""


def _iter_files(root: Path):
    if not root.exists():
        return
    for p in sorted(root.rglob("*")):
        rel = p.relative_to(root)
        if any(part in EXCLUDE_NAMES for part in rel.parts):
            continue
        if any(rel.parts[:len(prefix)] == prefix for prefix in EXCLUDE_REL_PREFIXES):
            continue
        if p.suffix == ".pyc":
            continue
        if p.is_file():
            yield p


def _transform_bytes(path: Path, data: bytes) -> bytes:
    if path.suffix.lower() in TEXT_SUFFIXES:
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            return data
        return text.replace(OLD_TOKEN, NEW_TOKEN).encode("utf-8")
    return data


def build_mirror(dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    for src_file in _iter_files(SRC):
        rel = src_file.relative_to(SRC)
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(_transform_bytes(src_file, src_file.read_bytes()))
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "_GENERATED.md").write_text(GENERATED_MARKER, encoding="utf-8")


def _stale_files(mirror: Path, fresh: Path) -> list[str]:
    a = {p.relative_to(mirror) for p in _iter_files(mirror)}
    b = {p.relative_to(fresh) for p in _iter_files(fresh)}
    out = []
    for rel in sorted(a | b):
        fa, fb = mirror / rel, fresh / rel
        if not fa.exists() or not fb.exists() or fa.read_bytes() != fb.read_bytes():
            out.append(str(rel))
    return out


def check() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / "skills"
        build_mirror(fresh)
        stale = _stale_files(DST, fresh)
    if stale:
        sys.stderr.write("[sync_codex_mirror] .codex/skills is STALE:\n")
        for rel in stale[:40]:
            sys.stderr.write(f"  - {rel}\n")
        if len(stale) > 40:
            sys.stderr.write(f"  ... and {len(stale) - 40} more\n")
        sys.stderr.write("  Fix: python scripts/sync_codex_mirror.py\n")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate/verify the .codex/skills mirror.")
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if the mirror is stale; do not write.")
    args = ap.parse_args()
    if args.check:
        return check()
    build_mirror(DST)
    print(f"[sync_codex_mirror] regenerated {DST} from {SRC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
